"""add assignee_id to vacancies

Revision ID: 0ad54a3b31eb
Revises: 5b59badb4550
Create Date: 2026-03-06 12:00:16.389281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ad54a3b31eb'
down_revision: Union[str, Sequence[str], None] = '5b59badb4550'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_logs_target_entity_id'), table_name='audit_logs')
    op.create_index('ix_audit_logs_target_entity_id', 'audit_logs', ['target_entity', 'id'], unique=False)
    op.drop_index(op.f('ix_employees_status_org_unit_id'), table_name='employees')
    op.drop_index(op.f('ix_financial_records_employee_id_id_desc'), table_name='financial_records')
    op.alter_column('login_logs', 'action',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_login_logs_timestamp'), table_name='login_logs')
    op.drop_index(op.f('ix_login_logs_user_id'), table_name='login_logs')
    op.drop_index(op.f('ix_login_logs_action_id'), table_name='login_logs')
    op.create_index('ix_login_logs_action_id', 'login_logs', ['action', 'id'], unique=False)
    op.create_index(op.f('ix_login_logs_id'), 'login_logs', ['id'], unique=False)
    op.drop_index(op.f('ix_notifications_user_id_is_read_id'), table_name='notifications')
    op.create_index('ix_notifications_user_id_is_read_id', 'notifications', ['user_id', 'is_read', 'id'], unique=False)
    op.drop_index(op.f('ix_request_history_request_id_id'), table_name='request_history')
    op.create_index('ix_request_history_request_id_id', 'request_history', ['request_id', 'id'], unique=False)
    op.drop_index(op.f('ix_salary_requests_requester_id_id'), table_name='salary_requests')
    op.create_index('ix_salary_requests_requester_id_id', 'salary_requests', ['requester_id', 'id'], unique=False)
    op.drop_index(op.f('ix_salary_requests_status_id'), table_name='salary_requests')
    op.create_index('ix_salary_requests_status_id', 'salary_requests', ['status', 'id'], unique=False)
    op.add_column('vacancies', sa.Column('assignee_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'vacancies', 'users', ['assignee_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vacancies', type_='foreignkey')
    op.drop_column('vacancies', 'assignee_id')
    op.drop_index('ix_salary_requests_status_id', table_name='salary_requests')
    op.create_index(op.f('ix_salary_requests_status_id'), 'salary_requests', ['status', sa.literal_column('id DESC')], unique=False)
    op.drop_index('ix_salary_requests_requester_id_id', table_name='salary_requests')
    op.create_index(op.f('ix_salary_requests_requester_id_id'), 'salary_requests', ['requester_id', sa.literal_column('id DESC')], unique=False)
    op.drop_index('ix_request_history_request_id_id', table_name='request_history')
    op.create_index(op.f('ix_request_history_request_id_id'), 'request_history', ['request_id', sa.literal_column('id DESC')], unique=False)
    op.drop_index('ix_notifications_user_id_is_read_id', table_name='notifications')
    op.create_index(op.f('ix_notifications_user_id_is_read_id'), 'notifications', ['user_id', 'is_read', sa.literal_column('id DESC')], unique=False)
    op.drop_index(op.f('ix_login_logs_id'), table_name='login_logs')
    op.drop_index('ix_login_logs_action_id', table_name='login_logs')
    op.create_index(op.f('ix_login_logs_action_id'), 'login_logs', ['action', sa.literal_column('id DESC')], unique=False)
    op.create_index(op.f('ix_login_logs_user_id'), 'login_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_login_logs_timestamp'), 'login_logs', ['timestamp'], unique=False)
    op.alter_column('login_logs', 'action',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_financial_records_employee_id_id_desc'), 'financial_records', ['employee_id', sa.literal_column('id DESC')], unique=False)
    op.create_index(op.f('ix_employees_status_org_unit_id'), 'employees', ['status', 'org_unit_id'], unique=False)
    op.drop_index('ix_audit_logs_target_entity_id', table_name='audit_logs')
    op.create_index(op.f('ix_audit_logs_target_entity_id'), 'audit_logs', ['target_entity', sa.literal_column('id DESC')], unique=False)
    # ### end Alembic commands ###
