"""add_formal_offer_fields

Revision ID: 24816de81345
Revises: ee17798f8bee
Create Date: 2026-02-21 15:32:36.276976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24816de81345'
down_revision: Union[str, Sequence[str], None] = 'ee17798f8bee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_offers', sa.Column('probation_period', sa.String(), nullable=True))
    op.add_column('job_offers', sa.Column('working_hours', sa.String(), nullable=True))
    op.add_column('job_offers', sa.Column('lunch_break', sa.String(), nullable=True))
    op.add_column('job_offers', sa.Column('non_compete_text', sa.String(), nullable=True))
    op.add_column('job_offers', sa.Column('president_name', sa.String(), nullable=True))
    op.add_column('job_offers', sa.Column('hr_name', sa.String(), nullable=True))
    op.add_column('job_offers', sa.Column('start_date', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_offers', 'start_date')
    op.drop_column('job_offers', 'hr_name')
    op.drop_column('job_offers', 'president_name')
    op.drop_column('job_offers', 'non_compete_text')
    op.drop_column('job_offers', 'lunch_break')
    op.drop_column('job_offers', 'working_hours')
    op.drop_column('job_offers', 'probation_period')
    # ### end Alembic commands ###
