"""add bonus_count

Revision ID: 5ce6bc3e920b
Revises: 7b60fe59c8c8
Create Date: 2026-02-23 16:35:09.559797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ce6bc3e920b'
down_revision: Union[str, Sequence[str], None] = '7b60fe59c8c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planning_lines', sa.Column('bonus_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('planning_lines', 'bonus_count')
    # ### end Alembic commands ###
