"""Create integration_settings table

Revision ID: 69c1d805db1b
Revises: 24589079f18f
Create Date: 2026-02-16 16:45:43.325630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69c1d805db1b'
down_revision: Union[str, Sequence[str], None] = '24589079f18f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('integration_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_name', sa.String(), nullable=True),
    sa.Column('api_key', sa.String(), nullable=True),
    sa.Column('client_id', sa.String(), nullable=True),
    sa.Column('client_secret', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('additional_params', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_integration_settings_id'), 'integration_settings', ['id'], unique=False)
    op.create_index(op.f('ix_integration_settings_service_name'), 'integration_settings', ['service_name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_integration_settings_service_name'), table_name='integration_settings')
    op.drop_index(op.f('ix_integration_settings_id'), table_name='integration_settings')
    op.drop_table('integration_settings')
    # ### end Alembic commands ###
