"""add_job_offers_table

Revision ID: 7a3bb1abc3b7
Revises: 9245e0c4dd19
Create Date: 2026-02-21 15:13:10.560779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a3bb1abc3b7'
down_revision: Union[str, Sequence[str], None] = '9245e0c4dd19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_offers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=True),
    sa.Column('candidate_name', sa.String(), nullable=False),
    sa.Column('candidate_email', sa.String(), nullable=True),
    sa.Column('position_title', sa.String(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('base_net', sa.Integer(), nullable=True),
    sa.Column('kpi_net', sa.Integer(), nullable=True),
    sa.Column('bonus_net', sa.Integer(), nullable=True),
    sa.Column('valid_until', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('manager_name', sa.String(), nullable=True),
    sa.Column('benefits', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['organization_units.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['organization_units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_offers_id'), 'job_offers', ['id'], unique=False)
    op.create_index(op.f('ix_job_offers_token'), 'job_offers', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_offers_token'), table_name='job_offers')
    op.drop_index(op.f('ix_job_offers_id'), table_name='job_offers')
    op.drop_table('job_offers')
    # ### end Alembic commands ###
