"""add security fields to job offers

Revision ID: 7b60fe59c8c8
Revises: 92170de8f1b1
Create Date: 2026-02-22 12:33:17.841317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b60fe59c8c8'
down_revision: Union[str, Sequence[str], None] = '92170de8f1b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_offers', sa.Column('candidate_phone', sa.String(), nullable=True))
    op.add_column('job_offers', sa.Column('access_code', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_offers', 'access_code')
    op.drop_column('job_offers', 'candidate_phone')
    # ### end Alembic commands ###
