"""add_signatories_to_job_offer

Revision ID: 92170de8f1b1
Revises: 24816de81345
Create Date: 2026-02-21 15:39:00.751679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92170de8f1b1'
down_revision: Union[str, Sequence[str], None] = '24816de81345'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_offers', sa.Column('signatories', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_offers', 'signatories')
    # ### end Alembic commands ###
