"""add_offer_customization_fields

Revision ID: ee17798f8bee
Revises: 7a3bb1abc3b7
Create Date: 2026-02-21 15:18:05.227250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee17798f8bee'
down_revision: Union[str, Sequence[str], None] = '7a3bb1abc3b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_offers', sa.Column('welcome_text', sa.String(), nullable=True))
    op.add_column('job_offers', sa.Column('description_text', sa.String(), nullable=True))
    op.add_column('job_offers', sa.Column('theme_color', sa.String(), nullable=True))
    op.add_column('job_offers', sa.Column('custom_sections', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_offers', 'custom_sections')
    op.drop_column('job_offers', 'theme_color')
    op.drop_column('job_offers', 'description_text')
    op.drop_column('job_offers', 'welcome_text')
    # ### end Alembic commands ###
